<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 2/25/18
 * Time: 2:07 PM
 *
 * The userpage.
 *
 * @var app\models\User $user - The current user.
 * @var \app\models\Token $token - The user's token.
 * @var \app\models\User[] $following - Users that the user has followed
 * @var \app\models\User[] $followers - Users that follow the user.
 * @var \app\models\UserEvent[] $events - Activity feed objects
 * @var \app\controllers\BaseController $this
 */
$title =  $user->getFullName()."'s Profile";

$js_init = '';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>
<script type="application/javascript">
    function unfollow(userId) {
        // hacky method to submit form from JS
        if (!confirm('Are you sure you want to unfollow this user?')) {
            return;
        }

        var url = '<?= $this->url('/users') ?>' + '/' + userId + '/unfollow';
        var $form = $('<form>', {
            action: url,
            method: 'post'
        });

        $('<input>').attr({
            type: "hidden",
            name: 'ref',
            value: '/users'
        }).appendTo($form);

        $form.appendTo('body').submit();
    }

    function follow(userId) {
        var url = '<?= $this->url('/users') ?>' + '/' + userId + '/follow';
        var $form = $('<form>', {
            action: url,
            method: 'post'
        });

        $('<input>').attr({
            type: "hidden",
            name: 'ref',
            value: '/users'
        }).appendTo($form);

        $form.appendTo('body').submit();
    }
</script>

<div class="row">
    <section class="col col-12 col-lg-4">
        <div class="my-4">
            <h2><?= $user->getFullName() ?></h2>
            <small class="text-muted"><?= $user->getUsername() ?></small>
        </div>
        <?php if ($this->getLoggedInUser()->getUserId() == $id): ?>
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2" role="group" aria-label="second group">
                <form action="<?= $_ENV['SUBDIRECTORY'] ?>/users/logout" method="post"
                      onsubmit="return confirm('Are you sure you want to log out?')">
                    <input type="submit" class="btn btn-warning" value="Log Out">
                </form>
            </div>

            <div class="btn-group mr-2" role="group" aria-label="second group">
                <form action="<?= $_ENV['SUBDIRECTORY'] ?>/users/delete" method="post"
                      onsubmit="return confirm('Are you sure you want to delete this account? (this cannot be undone)');">
                    <input type="submit" class="btn btn-danger" value="Delete Account">
                </form>
            </div>
            <div class="btn-group mr-2" role="group" aria-label="second group">
                <form action="<?= $_ENV['SUBDIRECTORY'] ?>/users/edit">
                    <input type="submit" class="btn btn-danger" value="Edit"/>
                </form>
            </div>
          <?php endif; ?>


        </div>

        <div class="mt-4 p-4 list-group-item">
            <p class="setting"><strong class="mr-2">First Name:</strong><?= $user->getFirstname() ?></p>
            <p class="setting"><strong class="mr-2">Last Name:</strong><?= $user->getLastname() ?></p>
            <p class="setting"><strong class="mr-2">Type:</strong><?= $user->getFancyType() ?></p>
            <p class="setting"><strong class="mr-2">Privacy:</strong><?= $user->getPrivacy() ?></p>
            <p class="setting"><strong class="mr-2">E-mail Address:</strong><?= $user->getEmail() ?></p>
            <p class="setting"><strong class="mr-2">Last Logged In:</strong><?= $token->getCreated() ?></p>
        </div>

        <div class="mt-4">
            <h3>Users Followed</h3>
            <ul class="list-group">
                <?php foreach ($following as $follow): ?>
                    <li class="list-group-item">
                        <?php
                        if ($follow->getType() == \app\models\User::TYPE_ADMIN) {
                            echo "<h6 class='mt-0 text-danger'> " . $follow->getFullName() . " (" . $follow->getUsername() . ")";
                            echo "<span class=\"ml-2 badge badge-secondary\">Administrator</span>";
                            echo "</h6>";
                        } elseif ($user->getType() == \app\models\User::TYPE_EDITOR) {
                            echo "<h6 class='mt-0 text-primary'> " . $follow->getFullName() . " (" . $follow->getUsername() . ")";
                            echo "<span class=\"ml-2 badge badge-secondary\">Editor</span>";
                            echo "</h6>";
                        } else {
                            echo "<h6 class='mt-0'> " . $follow->getFullName() . " (" . $follow->getUsername() . ")";
                            echo "</h6>";
                        }
                        ?>
                        <div>
                            <a href='<?= $this->url('/messages') ?>' class='btn btn-dark'>Message</a>
                            <a href="#" class="btn btn-dark">Unfollow</a>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>

        <div class="mt-4">
            <h3>Users Following</h3>
            <ul class="list-group">
                <?php foreach ($followers as $follower): ?>
                    <li class="list-group-item">
                        <?php
                        if ($follower->getType() == \app\models\User::TYPE_ADMIN) {
                            echo "<h6 class='mt-0 text-danger'> " . $follower->getFullName() . " (" . $follower->getUsername() . ")";
                            echo "<span class=\"ml-2 badge badge-secondary\">Administrator</span>";
                            echo "</h6>";
                        } elseif ($follower->getType() == \app\models\User::TYPE_EDITOR) {
                            echo "<h6 class='mt-0 text-primary'> " . $follower->getFullName() . " (" . $follower->getUsername() . ")";
                            echo "<span class=\"ml-2 badge badge-secondary\">Editor</span>";
                            echo "</h6>";
                        } else {
                            echo "<h6 class='mt-0'> " . $follower->getFullName() . " (" . $follower->getUsername() . ")";
                            echo "</h6>";
                        }
                        ?>
                        <button class="btn btn-dark" onclick="follow(<?= $follower->getUserId() ?>)">Follow</button>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </section>

    <section class="col col-12 col-lg-8">
        <?php include "app/views/_activity_feed.phtml"?>
    </section>
</div>

<?php
include "app/views/_footer.phtml"
?>

















