<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 2/28/18
 * Time: 2:29 PM
 */
?>
<!-- html (started in _header) -->
<!-- body (started in _header) -->
    <!-- div (started in _header) -->
        <footer id = "whiteTextDiv">
            <hr class="clear">

            <!--Footer, with links to a Donate, Contact and Social Media page-->
            <!--http://jsfiddle.net/BYEw5/-->
            <div class="footerDiv row">
              <div class="col-sm"><a href="http://www.paypal.me/leslieb98">Donate</a></div>
              <div class="col-sm"><a href="mailto:leslie6@vt.edu?Subject=In%20Their%20Own%20Words">Contact</a></div>
              <div class="col-sm">&copy; 2018, all rights reserved</div>
            </div>
        </footer>
    </div>
    <!-- Bootstrap JS: -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>
