<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 2/28/18
 * Time: 2:29 PM
 */
?>

<hr class="clear">

<!--Footer, with links to a Donate, Contact and Social Media page-->
<!--http://jsfiddle.net/BYEw5/-->
<div class="footerDiv">
  <div><a href="#">Donate</a></div>
  <div><a href="#">Contact</a></div>
  <div><a href="#">Follow Us</a></div>
</div>

</div>
<!-- Additional Footer Content goes here, if needed -->


</body>
</html>
