<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 2/28/18
 * Time: 2:29 PM
 */
?>

<hr class="clear">
<div id = "whiteTextDiv">
<!--Footer, with links to a Donate, Contact and Social Media page-->
<!--http://jsfiddle.net/BYEw5/-->
<div class="footerDiv">
  <div><a href="http://www.paypal.me/leslieb98">Donate</a></div>
  <div><a href="mailto:leslie6@vt.edu?Subject=In%20Their%20Own%20Words">Contact</a></div>
  <div>&copy; 2018, all rights reserved</div>
</div>
</div>
</div>
<!-- Additional Footer Content goes here, if needed -->


</body>
</html>
