<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 2/28/18
 * Time: 2:26 PM
 *
 * Generic header used on every page
 *
 * @var string $title - title of the page
 * @var string $js_init - any JS code to be run on page init
 * @var string $container_class - CSS class to use for the main container
 * @var string $container_id - ID to use for the main container
 * @var $this \app\controllers\BaseController
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>In Their Own Words </title>
    <link rel="stylesheet" href="<?= $_ENV['SUBDIRECTORY'] ?>/public/css/Style.css"/>

    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- FontAwesome -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
</head>
<body onload="<?= $js_init ?>">
<div id = "Header">
    <h1>In Their Own Words: World War II</h1>
</div>

<ul class="navbar">
    <li id="firstElement"><a id = "selected" href="<?= $_ENV['SUBDIRECTORY'] ?>/">Home</a></li>
    <li><a href="<?= $_ENV['SUBDIRECTORY'] ?>/about">About</a></li>
    <li><a href="<?= $_ENV['SUBDIRECTORY'] ?>/companies">Companies</a></li>
    <li><a href="<?= $_ENV['SUBDIRECTORY'] ?>/search"">Person Search</a></li>
    <!--li><button id = "logoutButtonContentSame" class="logoutButtonContentSame" onclick="">Logout</button></li-->
    <?php if($this->getLoggedInUser() != null): ?>
        <li><a href="<?= $_ENV['SUBDIRECTORY'] ?>/users"><?= $this->getLoggedInUser()->getUsername() ?></a></li>
        <li><a href="<?= $_ENV['SUBDIRECTORY'] ?>/users/logout">Log Out</a></li>
    <?php else: ?>
        <li><a href="<?= $_ENV['SUBDIRECTORY'] ?>/users/new">Create Account</a></li>
        <li><a href="<?= $_ENV['SUBDIRECTORY'] ?>/users/login">Log In</a></li>
    <?php endif; ?>
</ul>

<div id = "whiteTextDiv">
<div id="flashes">
    <i>
        <?php
        $flashes = $this->showFlashMessages();
        foreach ($flashes as $flash) {
            echo "<p class='flash ${flash['level']}'> ${flash['msg']}</pi()>";
        }
        ?>
    </i>
</div>
</div>

<div class="<?= $container_class ?>" id="<?= $container_id ?>">