<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 2/28/18
 * Time: 2:26 PM
 *
 * Generic header used on every page
 *
 * @var string $title - title of the page
 * @var string $js_init - any JS code to be run on page init
 * @var string $container_class - CSS class to use for the main container
 * @var string $container_id - ID to use for the main container
 * @var $this \app\controllers\BaseController
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $title ?> | In Their Own Words </title>

    <!-- Bootstrap CSS -->
    <!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"-->
	<link rel="stylesheet" href="https://bootswatch.com/4/solar/bootstrap.min.css">

    <!-- Our Stylesheet -->
    <link rel="stylesheet" href="<?= $_ENV['SUBDIRECTORY'] ?>/public/css/style-bs.css"/>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="<?= $_ENV['SUBDIRECTORY'] ?>/public/js/scripts-jquery.js"></script>
</head>

<body onload="<?= $js_init ?>">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
    <a class="navbar-brand" href="<?= $_ENV['SUBDIRECTORY'] ?>/">In Their Own Words: World War II</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-nav mr-auto">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?= $_ENV['SUBDIRECTORY'] ?>/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $_ENV['SUBDIRECTORY'] ?>/about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $_ENV['SUBDIRECTORY'] ?>/companies">Companies</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $_ENV['SUBDIRECTORY'] ?>/search">Search</a>
                </li>
                <?php if ($this->getLoggedInUser() != null): ?>
                  <li class="nav-item">
                      <a class="nav-link" href="<?= $_ENV['SUBDIRECTORY'] ?>/users/all">View Users</a>
                  </li>
                <?php endif; ?>
                 
                <li class="nav-item dropdown">
                    <?php if ($this->getLoggedInUser() != null): ?>

                        <a class="nav-link dropdown-toggle" href="<?= $_ENV['SUBDIRECTORY'] ?>/users"
                           id="navbarDropdown"
                           role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <?= $this->getLoggedInUser()->getUsername() ?>
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="<?= $_ENV['SUBDIRECTORY'] ?>/users/logout">Log Out</a>
                            <a class="dropdown-item" href="<?= $_ENV['SUBDIRECTORY'] ?>/users">User Profile</a>
                            <a class="dropdown-item" href="<?= $_ENV['SUBDIRECTORY'] ?>/messages">Messages</a>
                            <?php if($this->getLoggedInUser()->getType() == \app\models\User::TYPE_ADMIN): ?>
                                <a class="dropdown-item" href="<?= $this->url('/admin')?>">Admin Controls</a>
                            <?php endif; ?>
                        </div>
                    <?php else: ?>
                        <a class="nav-link dropdown-toggle" href="<?= $_ENV['SUBDIRECTORY'] ?>/users/login"
                           id="navbarDropdown"
                           role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Log In
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="<?= $_ENV['SUBDIRECTORY'] ?>/users/login">Log In</a>
                            <a class="dropdown-item" href="<?= $_ENV['SUBDIRECTORY'] ?>/users/new">Create Account</a>
                        </div>
                    <?php endif; ?>
                </li>
             </ul>
        </div>
    </div>
</nav>

<div id="whiteTextDiv">
    <div id="flashes">
        <i>
            <?php foreach ($this->showFlashMessages() as $flash): ?>
                <div class="alert alert-dismissible fade show <?= $flash['level'] ?>" role="alert">
                    <?= $flash['msg'] ?>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            <?php endforeach; ?>
        </i>
    </div>
</div>

<div class="<?= $container_class ?>" id="<?= $container_id ?>">
    <!-- Page content goes here -->
