<?php
$title = 'About';

$js_init = '';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>

<h2>About Division</h2>
<img src="" alt="Picture of Division"/>
<div id = "whiteTextDiv">
<p>About: The 786th Tank Battalion was formed on September 20, 1943. On November 28 of the same year, the battalion sailed off to Europe to help defeat the Axis Powers. The battalion was attached to the 99th Infantry Division. The battalion was disbanded on June 13, 1945 upon the ending of the war. One major contribution the battalion made towards the Allied Powers in World War II was their testing of the gyrostabilizer. The gyrostabilizer was used in tanks and helped keep guns stable while the tank was moving. </p>
</div>
<?php
include "app/views/_footer.phtml"
?>
