<?php
/**
 * The "about" page.
 *
 * @var $this \app\controllers\BaseController
 */

$title = 'About';

$js_init = 'getLocationImages(); init_ajax(\''. $_ENV['SUBDIRECTORY'] .'\', false, '. $this->getLoggedInUserType() .');';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>

<div class="row">
    <main class="col-12">
        <h2 class="mt-4">About Division</h2>
        <img class="img-fluid" src="public/img/786th.jpg" alt="Picture of Division" style="max-width: 100%"/>
        <div id="whiteTextDiv" class="mt-4">
            <i class="mt-2">Picture Source: <a href="http://hollowaypages.com/786th.htm">http://hollowaypages.com/786th.htm</a></i>
            <br>
            <br>
            <p>After the Allied troops successfully landed and secured the beachheads in Normandy, a successive chain of operations known as the Central Europe Campaign took place in order to bring the Third Reich to its knees. During this tenuous campaign, soldiers went through horrid fighting conditions and battles far bloodier than the original D-Day invasion. Along with monetary issues , challenges overlooked by the War department such as flooded valleys and dysfunctional transportation on the front lines plagued the rapid movement of the Allied troops.</p>
            <p>After gaining liberation from Nazi controlled Paris, the Allied force set its sights on the heart of the Third Reich. This advance would continue until the end of the war in Europe. The initial push into Western Germany was stalled near the Siegfried Line, a connected network of towns and cities secured with German troops. In order to flank the German troops and prevent the reinforcement of the Siegfried Line, the Allies pushed into the Hurtgen Forest. In addition, the offensive intent of the mission was to destroy the Roer River dams so that the Allies would be able to cross the river without them being cut off from supplies due to flooding. This 50 square mile area of land was later home to the planning site of the German counter-offensive known as the Ardennes Offensive or the Battle of the Bulge. The launch of this German attack effectively ended the Allied advance in the Hurtgen forest declaring a decisive German defensive victory.</p>
            <p>For approximately a month, the largest battle on the Western front was waged. The defeat of the Germans had finally allowed for a direct attack to push through the Siegfried Line and to cross the Rhine River into Germany. This site examines how individual soldiers fighting on these battles viewed their everyday lives and tasks by looking through the eyes of the 786th Tank Battalion. </p>
            <p>The 786th Tank Battalion was formed on September 20, 1943. On November 28 of the same year, the battalion
            sailed off to Europe to help defeat the Axis Powers. The battalion was attached to the 99th Infantry Division.
            The battalion was disbanded on June 13, 1945 upon the ending of the war. One major contribution the
            battalion made towards the Allied Powers in World War II was their testing of the gyrostabilizer. The gyrostabilizer
            was used in tanks and helped keep guns stable while the tank was moving. </p>

            <section class="my-4">
                <h3>Get Started</h3>
                <a href="<?= $this->url('/companies') ?>" class="btn btn-primary">View List of Companies</a>
                <a href="<?= $this->url('/users/new') ?>" class="btn btn-primary">Create Account</a>
            </section>

            <section class="my-4">
                <h3 class="my-2">
                    Timeline of Events
                    <?php if ($this->getLoggedInUserType() >=  2): ?>
                        <button class="btn btn-dark mx-4" id="eventAddBtn">Add</button>
                    <?php endif; ?>
                </h3>
                <ul class="list-unstyled" id="events-tbody">
                    <!--
                        AJAX
                     -->
                </ul>
            </section>

            <h3 class="mb-4"> Locations </h3>

            <ul class="list-unstyled">
                <li class="media">
                    <img class="mr-3" id="image1" src="" alt="New York, NY">
                    <div class="media-body">
                        <h5 class="mt-0 mb-1"><a href="https://en.wikipedia.org/wiki/New_York_Harbor">New York, New York</a></h5>
                    </div>
                </li>

                <li class="media my-4">
                    <img class="mr-3" id="image2" src=""" alt="Greenock, Scotland">
                    <div class="media-body">
                        <h5 class="mt-0 mb-1"><a href="https://en.wikipedia.org/wiki/Greenock">Greenock, Scotland</a></h5>
                    </div>
                </li>

                <li class="media my-4">
                    <img class="mr-3" id="image3" src=""" alt="Macclesfield, England">
                    <div class="media-body">
                        <h5 class="mt-0 mb-1"><a href="https://en.wikipedia.org/wiki/Macclesfield">Macclesfield, England</a></h5>
                    </div>
                </li>

                <li class="media my-4">
                    <img class="mr-3" id="image4" src=""" alt="Le Havre, France">
                    <div class="media-body">
                        <h5 class="mt-0 mb-1"><a href="https://en.wikipedia.org/wiki/Le_Havre">Le Havre, France</a></h5>
                    </div>
                </li>

                <li class="media my-4">
                    <img class="mr-3" id="image5" src=""" alt="Theux, Belgium">
                    <div class="media-body">
                        <h5 class="mt-0 mb-1"><a href="https://en.wikipedia.org/wiki/Theux">Theux, Belgium</a></h5>
                    </div>
                </li>
            </ul>

        </div>
    </main>
</div>

<?php if ($this->getLoggedInUser() && $this->getLoggedInUser()->getType() >= 2): ?>
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <form id="eventAdd">
                <div class="modal-header">
                    <h5 class="modal-title" id="addModalLabel">Add New Event</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <div class="form-group col col-12 col-lg-4">
                            <label for="type">Event Type</label>
                            <select class="form-control" name="type" id="" required>
                                <option value="event">Event</option>
                                <option value="battle">Battle</option>
                                <option value="diary">Diary</option>
                            </select>

                            <label for="eventName">Name</label>
                            <input type="text" class="form-control" name="eventName" placeholder="Name" required>

                            <label for="date">Event Date</label>
                            <input type="date" class="form-control" name="date" value="1944-01-01" required>

                            <label for="locationName" >Picture Query Term</label>
                            <input type="text" class="form-control" name="locationName" placeholder="Location Name" required>

                            <hr class="my-4">

                            <label for="latitude">Latitude</label>
                            <input type="number" class="form-control" name="latitude" placeholder="46.8207" step="any" required>
                            <label for="longitude">Longitude</label>
                            <input type="number" class="form-control" name="longitude" placeholder="-2.37545" step="any" required>

                            <input type="submit" class="btn btn-primary my-4 w-100" value="Add">
                        </div>
                        <div class="form-group col col-12 col-lg-8">
                            <label for="description">Event Notes</label>
                            <textarea name="description" class="form-control w-100 h-100" placeholder="Description of Event" required></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Submit">
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <form id="eventEdit">
                <div class="modal-header">
                    <h5 class="modal-title" id="editModalLabel">Add New Event</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <div class="form-group col col-12 col-lg-4">
                            <label for="editType">Event Type</label>
                            <select class="form-control" name="type" id="editType" required>
                                <option value="event" selected>Event</option>
                                <option value="battle">Battle</option>
                                <option value="diary">Diary</option>
                            </select>

                            <label for="editName">Name</label>
                            <input type="text" class="form-control" name="eventName" placeholder="Name" id="editName" required>

                            <label for="editDate">Event Date</label>
                            <input type="date" class="form-control" name="date" value="1944-01-01" id="editDate" required>

                            <label for="editLocationName" >Picture Query Term</label>
                            <input type="text" class="form-control" name="locationName" id="editLocationName" placeholder="Location Name" required>

                            <hr class="my-4">

                            <label for="editLatitude">Latitude</label>
                            <input type="number" class="form-control" name="latitude" id="editLatitude" placeholder="46.8207" step="any" required>
                            <label for="editLongitude">Longitude</label>
                            <input type="number" class="form-control" name="longitude" id="editLongitude" placeholder="-2.37545" step="any" required>
                        </div>
                        <div class="form-group col col-12 col-lg-8">
                            <label for="description">Event Notes</label>
                            <textarea id="editDescription" name="description" class="form-control w-100 h-100" placeholder="Description of Event" required></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Submit">
                </div>
            </form>
        </div>
    </div>
</div>
<?php endif; ?>

<script src="<?= $_ENV['SUBDIRECTORY'] ?>/public/js/scripts.js"></script>
<script src="<?= $_ENV['SUBDIRECTORY'] ?>/public/js/timeline_ajax.js"></script>

<?php
include "app/views/_footer.phtml"
?>
