<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 4/12/18
 * Time: 10:30 AM
 *
 * The Admin Panel.
 *
 * @var \app\models\Token $token
 * @var \app\models\User[] $users
 * @var \app\controllers\BaseController $this
 */
$title = 'Admin Control PANEL';

$js_init = '';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>
<h2 class="my-4">Admin Control Panel</h2>
<section class="my-4">
    <h4>Admins</h4>
    <table class="table">
        <thead><tr>
            <td>ID</td>
            <td>Username</td>
            <td>E-Mail</td>
            <td>Full Name</td>
            <td>Visibility</td>
            <td>Actions</td>
        </tr></thead>
        <tbody>
            <?php foreach ($users as $admin): ?><?php if($admin->getType() == \app\models\User::TYPE_ADMIN): ?>
                <tr>
                    <td><?= $admin->getUserId() ?></td>
                    <td><?= $admin->getUsername() ?></td>
                    <td><?= $admin->getEmail() ?></td>
                    <td><?= $admin->getFirstname() . ' ' . $admin->getLastname() ?></td>
                    <td><?= $admin->getPrivacy() ?></td>
                    <td class="btn-group" role="group">
                        <a href="<?= $this->url('/admin/edit/' . $admin->getUserId()) ?>" class="btn btn-warning">Edit</a>
                        <form action="<?= $this->url('/admin/delete/' . $admin->getUserId()) ?>"
                            onsubmit="confirm('Are you sure you want to delete this user account? THIS CANNOT BE UNDONE.')">
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>
                    </td>
                </tr>
            <?php endif; ?><?php endforeach; ?>
        </tbody>
    </table>
</section>
<section class="my-4">
    <h4>Editors</h4>
    <table class="table">
        <thead><tr>
            <td>ID</td>
            <td>Username</td>
            <td>E-Mail</td>
            <td>Full Name</td>
            <td>Visibility</td>
            <td>Actions</td>
        </tr></thead>
        <tbody>
        <?php foreach ($users as $editor): ?><?php if($editor->getType() == \app\models\User::TYPE_EDITOR): ?>
            <tr>
                <td><?= $editor->getUserId() ?></td>
                <td><?= $editor->getUsername() ?></td>
                <td><?= $editor->getEmail() ?></td>
                <td><?= $editor->getFirstname() . ' ' . $editor->getLastname() ?></td>
                <td><?= $editor->getPrivacy() ?></td>
                <td class="btn-group" role="group">
                    <a href="<?= $this->url('/admin/edit/' . $editor->getUserId()) ?>" class="btn btn-warning">Edit</a>
                    <form action="<?= $this->url('/admin/delete/' . $editor->getUserId()) ?>"
                          onsubmit="confirm('Are you sure you want to delete this user account? THIS CANNOT BE UNDONE.')">
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </form>
                </td>
            </tr>
        <?php endif; ?><?php endforeach; ?>
        </tbody>
    </table>
</section>
<section class="my-4">
    <h4>Commenters</h4>
    <table class="table">
        <thead><tr>
            <td>ID</td>
            <td>Username</td>
            <td>E-Mail</td>
            <td>Full Name</td>
            <td>Visibility</td>
            <td>Actions</td>
        </tr></thead>
        <tbody>
        <?php foreach ($users as $commenter): ?><?php if($commenter->getType() == \app\models\User::TYPE_COMMENTER): ?>
            <tr>
                <td><?= $commenter->getUserId() ?></td>
                <td><?= $commenter->getUsername() ?></td>
                <td><?= $commenter->getEmail() ?></td>
                <td><?= $commenter->getFirstname() . ' ' . $commenter->getLastname() ?></td>
                <td><?= $commenter->getPrivacy() ?></td>
                <td class="btn-group" role="group">
                    <a href="<?= $this->url('/admin/edit/' . $commenter->getUserId()) ?>" class="btn btn-warning">Edit</a>
                    <form action="<?= $this->url('/admin/delete/' . $commenter->getUserId()) ?>"
                          method="post"
                          onsubmit="confirm('Are you sure you want to delete this user account? THIS CANNOT BE UNDONE.')">
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </form>
                </td>
            </tr>
        <?php endif; ?><?php endforeach; ?>
        </tbody>
    </table>
</section>
<?php
include "app/views/_footer.phtml"
?>
