<?php
/**
 * The companies list.
 *
 * @var $companies \app\models\Unit[]
 */
$title = 'Companies';

$js_init = '';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>

<div id="whiteTextDiv">
    <h2>Companies</h2>
    <?php if ($this->is_logged_in()): ?>
        <!-- Display 'add' button if logged in: -->
        <form action="<?= $this->url('/companies/add') ?>" method="post">
            <input type="submit" value="Add New Company...">
        </form>
    <?php else: ?>
        <p><i>Log in to add new companies.</i></p>
    <?php endif; ?>
    <ul>
        <!-- Display companies in list form: -->
        <?php foreach ($companies as $company): ?>
            <li>
                <u><a href="<?= $_ENV['SUBDIRECTORY'] . "/companies/" . $company->getId() ?>"
                      id="noLeft"><?= $company->getName() ?></a></u>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<?php
include "app/views/_footer.phtml"
?>

