<?php
/**
 * @var $companies \app\models\Unit[]
 */
$title = 'Companies';

$js_init = '';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>

<div id = "whiteTextDiv">
<h2>Companies</h2>
    <?php if ($this->is_logged_in()): ?>
        <form action="<?= $this->url('/companies/add') ?>" method="post">
            <input type="submit" value="Add New Company...">
        </form>
    <?php else: ?>
        <p>Log in to add new companies.</p>
    <?php endif; ?>
    <ul>
        <?php foreach ($companies as $company): ?>
            <li>
                <a href="<?= $_ENV['SUBDIRECTORY'] . "/companies/" . $company->getId() ?>"><?= $company->getName() ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<?php
include "app/views/_footer.phtml"
?>

