<?php
/**
 * The companies list.
 *
 * @var $companies \app\models\Unit[]
 */
$title = 'Companies';

$js_init = '';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>

<div class="row">
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <script type="application/javascript">
        // testing values for NPM seerver
        window.backend = "<?= $_ENV['SUBDIRECTORY'] ?>";
        window.userlevel = <?= $this->getLoggedInUserType() ?>;
    </script>
    <div class="container p-4" id="root"></div>
    <script type="text/javascript" src="<?= $_ENV['SUBDIRECTORY'] ?>/public/js/companyViz.js"></script>

    <main id="whiteTextDiv" class="col-12">
        <h2 class="mt-4">Companies</h2>
        <div class="mt-4 mb-4">
            <?php if ($this->is_logged_in()): ?>
                <!-- Display 'add' button if logged in: -->
                <form action="<?= $this->url('/companies/add') ?>" method="post">
                    <input class="btn btn-primary" type="submit" value="Add New Company...">
                </form>
            <?php else: ?>
                <p><i>Log in to add new companies.</i></p>
            <?php endif; ?>
        </div>
        <ul class="list-group">
            <!-- Display companies in list form: -->
            <?php foreach ($companies as $company): ?>
                <li class="list-group-item list-group-item-action"
                    onclick="window.location.href='<?= $_ENV['SUBDIRECTORY'] . "/companies/" . $company->getId() ?>'" style="cursor: pointer">
                    <div class="media">
                        <img class="mr-3 align-self-center w-25" src="<?= $company->getPhotoFileURL() ?>">
                        <div class="media-body">
                            <h5 class="mt-0"><?= $company->getName() ?></h5>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </main>
</div>

<?php

include "app/views/_footer.phtml"
?>

