<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 4/4/18
 * Time: 10:03 AM
 *
 * The "credits" page.
 */

$title = 'Credits';

$js_init = 'getLocationImages();';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>

<h2 class="my-4">Credits</h2>
<section>
    <p>Created by Wes Jordan, Kayla Moore, Leslie Blustein, and Raghu Srinivasan, with assistance of Robby Hetrick
        for <strong>CS 3744</strong> as a class project.</p>
    <h4>Frameworks Used</h4>
    <ul>
        <li>Bootstrap 4.0</li>
        <li>jQuery 3.3.1</li>
        <li>XAMPP 7.2 (backend)</li>
    </ul>
    <h4>Image Credits</h4>
    <ul>
        <li>???</li>
    </ul>
</section>

<?php
include "app/views/_footer.phtml"
?>
