<?php
$title = 'Event Page';
$js_init = '';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>
<!--link rel="stylesheet" type="text/css" href="Style.css" /-->
<img src="" alt="Image of Event"/>
<div id="details">
<h2>Name of Event</h2>
<p> Location: </p>
<p> Year: </p>
<p> Description: </p>
</div>
<div id="docs">
  <h3> Documents </h3>
  
</div>
<?php include  "app/views/_footer.phtml" ?>
