<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 2/24/18
 * Time: 11:34 AM
 *
 * The site root.
 *
 * @var \app\controllers\BaseController $this
 */
$title = 'Home';
$js_init = "";
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>
    <style>
        .carousel-inner img {
            width: 100%;
            max-height: 600px;
        }
    </style>

    <!-- Bootstrap Carousel: https://getbootstrap.com/docs/4.0/components/carousel/ -->
    <div id="row bsCarousel" class="carousel slide" data-ride="carousel">
        <!-- indicators -->
        <ol class="carousel-indicators">
            <li data-target="#bsCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#bsCarousel" data-slide-to="1"></li>
            <li data-target="#bsCarousel" data-slide-to="2"></li>
        </ol>
        <!-- carousel images -->
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="<?= $_ENV['SUBDIRECTORY'] ?>/public/img/war1.JPG" id="bannerPhotos" alt="Photo of WW2">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Read Their Stories</h5>
                </div>
            </div>
            <div class="carousel-item">
                <img style="" src="<?= $_ENV['SUBDIRECTORY'] ?>/public/img/war2.JPG" id="bannerPhotos2" alt="Photo of WW2">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Follow Their Journey</h5>
                </div>
            </div>
            <div class="carousel-item">
                <img src="<?= $_ENV['SUBDIRECTORY'] ?>/public/img/war3.JPG" id="bannerPhotos3" alt="Photo of WW2">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Learn history - in a new way</h5>
                </div>
            </div>
        </div>
        <!-- controls -->
        <a class="carousel-control-prev" href="#bsCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#bsCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <!--Information about the site, on the bottom of the main page-->
    <div class="row media" id="bottom">
        <!--img class="mr-3" src="..." alt="Generic placeholder image"-->
        <div class="media-body">
            <h2 class="mt-0">In Their Own Words: World War II</h2>
            <p class="welcomeText">Follow the journey of 786th Battalion as they fought for the Allied Powers during World
                War II.</p>
            <p class="welcomeText">Read, in their own words, the struggles they went through.</p>
            <p class="welcomeText">Create an account today to begin your journey.</p>        </div>
    </div>

<?php include "app/views/_footer.phtml" ?>