<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 2/24/18
 * Time: 11:34 AM
 *
 * The site root.
 *
 * @var \app\controllers\BaseController $this
 */
$title = 'Home';
$logged_in = $this->is_logged_in() ? 'true' : 'false';

$js_init = "init_index($logged_in)";
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>

    <!--h1>CS3744 Project 4</h1-->

    <!--Slideshow on Main Page-->
    <!--https://www.w3schools.com/howto/howto_js_slideshow.asp -->
    <div class="slideshow-container">

        <!-- Full-width images with number and caption text -->
        <div class="mySlides fade">
            <div class="numbertext">1 / 3</div>
            <img src="<?= $_ENV['SUBDIRECTORY'] ?>/public/img/war1.JPG" id="bannerPhotos" alt="Photo of WW2">
            <div class="text">Read their Stories</div>
        </div>

        <!-- Second Image-->
        <div class="mySlides fade">
            <div class="numbertext">2 / 3</div>
            <img src="<?= $_ENV['SUBDIRECTORY'] ?>/public/img/war2.JPG" id="bannerPhotos2" alt="Photo of WW2">
            <div class="text">Follow their Journey</div>
        </div>

        <!-- Third Image -->
        <div class="mySlides fade">
            <div class="numbertext">3 / 3</div>
            <img src="<?= $_ENV['SUBDIRECTORY'] ?>/public/img/war3.JPG" id="bannerPhotos3" alt="Photo of WW2">
            <div class="text">Learn history - in a new way</div>
        </div>

        <!-- Next and previous buttons -->
        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
        <a class="next" onclick="plusSlides(1)">&#10095;</a>
    </div>
    <br>

    <!-- The dots/circles -->
    <div id="allDots">
        <span class="dot" onclick="currentSlide(1)"></span>
        <span class="dot" onclick="currentSlide(2)"></span>
        <span class="dot" onclick="currentSlide(3)"></span>
    </div>


    <!--Information about the site, on the bottom of the main page-->
    <div id="bottom">
        <div id="welcomeTitle">
            <h2>In Their Own Words: World War II</h2>
        </div>

        <p class="welcomeText">Follow the journey of 786th Battalion as they fought for the Allied Powers during World
            War II.</p>
        <p class="welcomeText">Read, in their own words, the struggles they went through.</p>
        <p class="welcomeText">Create an account today to begin your journey.</p>
    </div>

    </body>

    <!--Needed to make slideshow start!  Note that the validator doesn't like
    this, but if I remove it the slideshow breaks :( -->
    <script src="<?= $_ENV['SUBDIRECTORY'] ?>/public/js/scripts.js"></script>

    </html>

<?php include "app/views/_footer.phtml" ?>