<!--Navigation Menu-->

<div id = "Header">
  <h1>In Their Own Words: World War II</h1>
</div>

<ul>
  <li><a id = "selected" href="<?= $_ENV['SUBDIRECTORY'] ?>/">Home</a></li>
  <li><a href="<?= $_ENV['SUBDIRECTORY'] ?>/about">About</a></li>
  <li><a href="#">Companies</a></li>
  <li><a href="#">People</a></li>
  <!--li><button id = "logoutButtonContentSame" class="logoutButtonContentSame" onclick="">Logout</button></li-->
  <li><a href="<?= $_ENV['SUBDIRECTORY'] ?>/users/new">Create Account</a></li>
  <li><a href="<?= $_ENV['SUBDIRECTORY'] ?>/users/login">Log In</a></li>
</ul>