<?php
/**
 * The search page.
 *
 * @var $isResults bool
 * @var $results mixed
 * @var $this \app\controllers\BaseController
 */

$title = 'Search';

$js_init = '';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>

<h2 class="my-4">Search</h2>

<main class="row">
    <section class="col col-12 col-md-3 border rounded my-4 p-4">
        <h6 class="my-2 w-100">Person Search:</h6>
        <form action='<?= $this->url("/search") ?>'>
            <label class="" for="fname">First Name</label>
            <input type="text" class="form-control mb-2" id="fname" name="firstname" placeholder="First Name">
            <label class="mr-3" for="lname">Last Name</label>
            <input type="text" class="form-control mb-2" id="lname" name="lastname" placeholder="Last Name">
            <input class="mb-2 btn btn-primary" type="submit" value="Search" id="submitFancy">
        </form>
    </section>

    <section class="col col-12 col-md-9">
        <?php if ($isResults): ?>
            <h6 class="my-2 w-100">Search Results:</h6>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Company</th>
                </tr>
                </thead>
                <tbody>
                <?php if (sizeof($results) == 0): ?>
                    <tr>
                        <td colspan="2">No results found.</td>
                    </tr>
                <?php else: ?>
                    <?php foreach ($results as $result): ?>
                        <tr>
                            <td><?= $result['person']->getName() ?></td>
                            <td><a href="<?= $this->url('/companies/' . $result['person']->getUnitID()) ?>">
                                    <?= $result['unitName'] ?>
                                </a></td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
        <?php endif; ?>
    </section>
</main>



<?php
include "app/views/_footer.phtml"
?>
