<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 2/25/18
 * Time: 2:29 PM
 *
 * The create account page.
 */
$title = 'New User';

$js_init = '';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>

<h2>Create User Account</h2>
<div id = "whiteTextDiv">
<i>*required</i>
<form action="<?= $_ENV['SUBDIRECTORY'] ?>/users/new" method="post" id="new-user-table">
    <table>
        <tbody>
            <tr>
                <td>Username(must be 7 or more characters)*</td>
                <td><input type="text" name="username" placeholder="Username" required minlength="7"></td>
            </tr>
            <tr>
                <td>Password (must be 7 or more characters)*</td>
                <td><input type="password" name="password" placeholder="Password" required minlength="7"></td>
            </tr>
            <tr>
                <td>E-mail*</td>
                <td><input type="email" name="email" placeholder="Email" required></td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td><span> </span></td>
                <td><input type="submit"><br></td>
            </tr>
        </tfoot>
    </table>
</form>
</div>

<?php
include "app/views/_footer.phtml"
?>