<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 2/26/18
 * Time: 2:32 PM
 *
 * The log-in page.
 */
$title = 'Log In';

$js_init = '';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>

<div id = "whiteTextDiv">

<span>No account?  <a href="<?= $_ENV['SUBDIRECTORY'] ?>/users/new">Create a new one.</a></span>

<div class="login" id="loginBox">
<form action="<?= $_ENV['SUBDIRECTORY'] ?>/users/login" method="post">
    <label>
        <!--Username-->
        <input type="text" name="username" placeholder="Username" id = "username" required>
    </label>
    <label>
        <!--Password-->
        <input type="password" name="password" placeholder="Password" id = "password" required>
    </label>
    
    <input type="submit" id = "signInButton">
</form>
</div>
</div>

<?php
include "app/views/_footer.phtml"
?>