<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 2/25/18
 * Time: 2:07 PM
 *
 * The userpage.
 *
 * @var app\models\User $user - The current user.
 * @var \app\models\Token $token - The user's token.
 * @var \app\models\User[] $following - Users that the user has followed
 * @var \app\models\User[] $followers - Users that follow the user.
 * @var \app\controllers\BaseController $this
 */
$title = 'My Profile';

$js_init = '';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>
<div class="row">
    <section class="col col-12 col-lg-4">
        <div class="my-4">
            <h2><?= $user->getFullName() ?></h2>
            <small class="text-muted"><?= $user->getUsername() ?></small>
        </div>

        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2" role="group" aria-label="second group">
                <form action="<?= $_ENV['SUBDIRECTORY'] ?>/users/logout" method="post"
                      onsubmit="return confirm('Are you sure you want to log out?')">
                    <input type="submit" class="btn btn-warning" value="Log Out">
                </form>
            </div>

            <div class="btn-group mr-2" role="group" aria-label="second group">
                <form action="<?= $_ENV['SUBDIRECTORY'] ?>/users/delete" method="post"
                      onsubmit="return confirm('Are you sure you want to delete this account? (this cannot be undone)');">
                    <input type="submit" class="btn btn-danger" value="Delete Account">
                </form>
            </div>

            <div class="btn-group mr-2" role="group" aria-label="second group">
                <form action="<?= $_ENV['SUBDIRECTORY'] ?>/users/edit">
                    <input type="submit" class="btn btn-danger" value="Edit"/>
                </form>
            </div>

        </div>

        <div class="mt-4 p-4 list-group-item">
            <p class="setting"><strong class="mr-2">First Name:</strong><?= $user->getFirstname() ?></p>
            <p class="setting"><strong class="mr-2">Last Name:</strong><?= $user->getLastname() ?></p>
            <p class="setting"><strong class="mr-2">Type:</strong><?= $user->getFancyType() ?></p>
            <p class="setting"><strong class="mr-2">Privacy:</strong><?= $user->getPrivacy() ?></p>
            <p class="setting"><strong class="mr-2">E-mail Address:</strong><?= $user->getEmail() ?></p>
            <p class="setting"><strong class="mr-2">Last Logged In:</strong><?= $token->getCreated() ?></p>
        </div>

        <div class="mt-4">
            <h3>Followed Users</h3>
            <ul class="list-group">
                <?php foreach ($following as $user): ?>
                    <li class="list-group-item">
                        <?php
                        if ($user->getType() == \app\models\User::TYPE_ADMIN) {
                            echo "<h6 class='mt-0 text-danger'> " . $user->getFullName() . " (" . $user->getUsername() . ")";
                            echo "<span class=\"ml-2 badge badge-secondary\">Administrator</span>";
                            echo "</h6>";
                        } elseif ($user->getType() == \app\models\User::TYPE_EDITOR) {
                            echo "<h6 class='mt-0 text-primary'> " . $user->getFullName() . " (" . $user->getUsername() . ")";
                            echo "<span class=\"ml-2 badge badge-secondary\">Editor</span>";
                            echo "</h6>";
                        } else {
                            echo "<h6 class='mt-0'> " . $user->getFullName() . " (" . $user->getUsername() . ")";
                            echo "</h6>";
                        }
                        ?>
                        <div>
                            <a href="<?= $this->url('/messages') ?>" class="btn btn-dark">Message</a>
                            <a href="#" class="btn btn-dark">Unfollow</a>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>

        <div class="mt-4">
            <h3>Following Users</h3>
            <ul class="list-group">
                <?php foreach ($followers as $user): ?>
                    <li class="list-group-item">
                        <?php
                        if ($user->getType() == \app\models\User::TYPE_ADMIN) {
                            echo "<h6 class='mt-0 text-danger'> " . $user->getFullName() . " (" . $user->getUsername() . ")";
                            echo "<span class=\"ml-2 badge badge-secondary\">Administrator</span>";
                            echo "</h6>";
                        } elseif ($user->getType() == \app\models\User::TYPE_EDITOR) {
                            echo "<h6 class='mt-0 text-primary'> " . $user->getFullName() . " (" . $user->getUsername() . ")";
                            echo "<span class=\"ml-2 badge badge-secondary\">Editor</span>";
                            echo "</h6>";
                        } else {
                            echo "<h6 class='mt-0'> " . $user->getFullName() . " (" . $user->getUsername() . ")";
                            echo "</h6>";
                        }
                        ?>
                        <a href="#" class="btn btn-dark">Follow</a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </section>

    <section class="col col-12 col-lg-8">
        <h3 class="my-4">Activity Feed</h3>
        <ul class="list-unstyled">
            <?php foreach ([1, 2, 3, 4, 5, 6, 7] as $i): ?>
                <?php if ($i % 3 == 0): ?>
                    <li class="alert alert-secondary">
                        <h5 class="alert-heading">Joe Bob commented on <a href="<?= $this->url('/companies/1') ?>"
                                                                          class="alert-link">Assault Gun Platoon</a>:
                        </h5>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent accumsan ultrices luctus.
                            Praesent sodales ex convallis sem laoreet tincidunt. Ut bibendum neque felis, bibendum
                            hendrerit tellus laoreet eget. Nam vehicula sagittis lacus quis tempor. Donec id ex et
                            ligula viverra ornare. Maecenas at mattis nunc, eu hendrerit quam. Praesent lacus magna,
                            blandit volutpat aliquam at, egestas ac felis. Cras accumsan condimentum turpis, id auctor
                            magna. Cras aliquet nunc nisi, id lobortis diam accumsan a. In ac gravida velit. Nulla
                            facilisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus
                            mus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos
                            himenaeos. Ut vitae neque velit. Praesent metus tellus, suscipit vitae auctor quis, sodales
                            non arcu.</p>
                        <hr>
                        <p><?= $i * 5 ?> minutes ago</p>
                    </li>
                <?php elseif ($i % 3 == 1): ?>
                    <li class="alert alert-success">
                        <h5 class="alert-heading">Joe Bob followed you!:</h5>
                        <p>Click <a href="#" class="alert-link">here</a> to follow them back.</p>
                        <hr>
                        <p><?= $i * 5 ?> minutes ago</p>
                    </li>
                <?php else: ?>
                    <li class="alert alert-primary">
                        <h5 class="alert-heading">Joe Bob sent you a message:</h5>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent accumsan ultrices luctus.
                            Praesent sodales ex convallis sem laoreet tincidunt. Ut bibendum neque felis, bibendum
                            hendrerit tellus laoreet eget. Nam vehicula sagittis lacus quis tempor. Donec id ex et
                            ligula viverra ornare. Maecenas at mattis nunc, eu hendrerit quam. Praesent lacus magna,
                            blandit volutpat aliquam at, egestas ac felis. Cras accumsan condimentum turpis, id auctor
                            magna. Cras aliquet nunc nisi, id lobortis diam accumsan a. In ac gravida velit. Nulla
                            facilisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus
                            mus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos
                            himenaeos. Ut vitae neque velit. Praesent metus tellus, suscipit vitae auctor quis, sodales
                            non arcu.</p>
                        <hr>
                        <p><?= $i * 5 ?> minutes ago</p>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
            <a href="#" class="btn btn-secondary">Back to top</a>
        </ul>
    </section>
</div>

<?php
include "app/views/_footer.phtml"
?>
