<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 2/25/18
 * Time: 2:07 PM
 *
 * The userpage.
 *
 * @var app\models\User $user - The current user.
 * @var \app\models\Token $token - The user's token.
 */
$title = 'User: '.$user->getUsername();

$js_init = '';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>
    <h1>User: <?= $user->getUsername() ?></h1>
    <ul>
        <li>Email: <?= $user->getEmail() ?></li>
        <li>Token Created: <?= $token->getCreated() ?></li>
        <li>Token Expires: <?= $token->getExpires() ?></li>
    </ul>
    <form action="<?= $_ENV['SUBDIRECTORY'] ?>/users/logout" method="post" onsubmit="return confirm('Are you sure you want to log out?')">
        <input type="submit" value="Log Out">
    </form>
    <form action="<?= $_ENV['SUBDIRECTORY'] ?>/users/delete" method="post" onsubmit="return confirm('Are you sure you want to delete this account? (this cannot be undone)');">
        <input type="submit" value="Delete User">
    </form>
<?php
include "app/views/_footer.phtml"
?>
