<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 2/25/18
 * Time: 2:29 PM
 *
 * The create account page.
 */
$title = 'New User';

$js_init = '';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>
    <h2 class="my-4">Create User Account</h2>
    <main class="row border rounded my-4 p-4">
        <form action="<?= $_ENV['SUBDIRECTORY'] ?>/users/new" method="post">
            <label for="username">Username</label>
            <input type="text" class="form-control" name="username" placeholder="Username" required minlength="7">
            <small class="form-text text-muted mb-2">Required; must be seven or more characters long; must be unique.
            </small>

            <label for="Password">Password</label>
            <input type="password" class="form-control" name="password" placeholder="Password" required minlength="7">
            <small class="form-text text-muted mb-2">Required; must be seven or more characters long.</small>

            <label for="email">Email Address</label>
            <input type="email" class="form-control" name="email" placeholder="sample@email.com" required>
            <small class="form-text text-muted mb-2">Required</small>

            <input type="submit" class="btn btn-primary" value="Create New Account">
        </form>
    </main>

<?php
include "app/views/_footer.phtml"
?>