<?php
/**
 * Created by PhpStorm.
 * User: wes
 * Date: 2/25/18
 * Time: 2:07 PM
 *
 * The userpage.
 *
 * @var app\models\User $user - The current user.
 * @var \app\models\Token $token - The user's token.
 */
$title = 'My Profile';

$js_init = '';
$container_class = 'container';
$container_id = 'container';
include "app/views/_header.phtml"
?>
<!--Shows the user's settings and account information-->
<section id="settings">
    <h2><?= $user->getUsername() ?></h2>
    <form action="<?= $_ENV['SUBDIRECTORY'] ?>/users/logout" method="post" onsubmit="return confirm('Are you sure you want to log out?')">
        <input type="submit" value="Log Out">
    </form>
    <br>
    <form action="<?= $_ENV['SUBDIRECTORY'] ?>/users/delete" method="post" onsubmit="return confirm('Are you sure you want to delete this account? (this cannot be undone)');">
        <input type="submit" value="Delete Account">
    </form>

    <p class="setting"><span>E-mail Address</span><?= $user->getEmail() ?></p>

    <p class="setting"><span>Last Logged In</span><?= $token->getCreated() ?></p>

</section>

<?php
include "app/views/_footer.phtml"
?>